### PR TITLE
sorted lists in alphabetical order

### PR DESCRIPTION
**Pull request by varsha-kss**
sorted the lists of newsletters in alphabetical order

### CODE REVIEW

**Comment by varsha-kss** [comment]
please merge this pr under hacktoberfest-accepted label. Thank you!

**Comment by jdwilkin4** [comment]
HI @varsha-kss ! 

We will review your PR.
But also, the `hacktoberfest-accepted` label is technically optional. 
Any PR submitted and approved under a repo with the `hacktoberfest` topic will automatically count towards Hacktoberfest 👍 

I personally like to use it just to keep track of how many PR we have during hacktoberfest but it is technically optional 👍

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by varsha-kss** [comment]
Okay Thank you so much for the info ma'am 😊! Also glad I could make a contribution in this repository, thanks for answering my queries throughout!

**Pull request merged**
